### ISSUE TITLE
Can't find cmdline.py (twitter 1.10.0)

### ISSUE THREAD

**Issue by slauria** [sixohsix/twitter#162] opened 2013-06-22 17:43 UTC
After clean install (pip uninstall twitter and then easy_install twitter) I have the 
"ImportError: No module named cmdline".

Previous version of twitter (v1.9.4) was working fine until API V 1 no longer supported.

**Comment by hugovk** [comment] 2017-10-19 08:58
These three look like duplicates: #67 #162 #281.

**Comment by sixohsix** [comment] 2017-10-19 09:38
Yep, dupe of #67.

**Closed by sixohsix** 2017-10-19 09:38 UTC
Labels: CLI
