### ISSUE TITLE
ImportError: No module named cmdline

### ISSUE THREAD

**Issue by hillz1** [sixohsix/twitter#281] opened 2015-02-24 02:00 UTC
I have successfully installed version 1.16.0 but when I try to run "twitter" from my linux terminal it says like this: http://s17.postimg.org/wim9qyqnz/angel_beats_bg5.jpg

I had no error in version 1.15.0

**Comment by hugovk** [comment] 2017-10-19 08:58
These three look like duplicates: #67 #162 #281.

**Comment by sixohsix** [comment] 2017-10-19 09:38
Yep. Dupe of #67,

**Closed by sixohsix** 2017-10-19 09:38 UTC
Labels: CLI
