### ISSUE TITLE
def auto_follow does not continue loop once it hit's a user that has blocked you

### ISSUE THREAD

**Issue by davebeaumont** [sixohsix/twitter#334] opened 2016-06-12 16:56 UTC
C:\Twitter\twitter-master>python sample_twitter_codes.py
error: Twitter sent status 403 for URL: 1.1/friendships/create.json using parameters: (follow=False&oauth_consumer_key=**HIDDEN**&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1465750327&oauth_token=**HIDDEN**&oauth_version=1.0&user_id=**HIDDEN**&oauth_signature=**HIDDEN**)
details: {'errors': [{'message': 'You have been blocked from following this account at the request of the user.', 'code': 162}]}

I have not really touched Python development but will have a further look if I get time.

**Comment by miv-ableton** [comment] 2016-06-13 09:45
I don't see the `auto_follow` function, nor the `sample_twitter_codes.py` file in this project. Where is it?

**Comment by hugovk** [comment] 2016-06-13 10:19
Looks like it's from one of these spammy-looking repos:
https://github.com/ProgrammingforMarketers/grow-twitter-following
https://github.com/tron1991/Automate-Twitter-Followers-Python

@davebeaumont I suggest you report the issue at whichever repo you got your code from, or share here a minimal code example needed to reproduce the problem, ideally using this twitter module directly without third-party apps.

@sixohsix I suggest you close this in the meantime.

**Closed** 2016-06-13 10:28 UTC
